import { useState } from 'react'
const PHONE = '96898778983'
const INITIAL = [0,1,2,3,4,5,6,7,8]
const PROMPTS = [
 {id:'prayer',text:'يا ربنا احفظ لنا جلالة السلطان',emoji:'🙏🏻',answer:'prayer'},
 {id:'people',text:'والشعب في الأوطان',emoji:'🧒🏻👧🏻',answer:'people'},
 {id:'pride',text:'بالعز والأمان',emoji:'👮🏻‍♂️',answer:'police'},
 {id:'sky',text:'فارقتي هام السماء',emoji:'☁️🌤️',answer:'sky'},
]
const PICTURES = [{id:'sky',label:'السماء',emoji:'☁️🌤️'},{id:'people',label:'الشعب العُماني',emoji:'🧒🏻👧🏻'},{id:'prayer',label:'دعاء',emoji:'🙏🏻'},{id:'police',label:'شرطة عُمان السلطانية',emoji:'👮🏻‍♂️'}]
export default function BookActivities({lessonTitle}:{lessonTitle:string}) {
 const [name,setName]=useState(''),[grade,setGrade]=useState('')
 const [tiles,setTiles]=useState(()=>[3,0,7,2,5,1,8,4,6]),[selected,setSelected]=useState<number|null>(null)
 const [matches,setMatches]=useState<Record<string,string>>({}),[dragged,setDragged]=useState<string|null>(null)
 const anthem=lessonTitle==='النشيد الوطني'||lessonTitle==='نشيد (عَلَم بلادي)'
 const full=name.trim().split(/\s+/).filter(Boolean).length>=4
 const puzzleDone=tiles.every((v,i)=>v===i)
 const matchDone=PROMPTS.every(p=>matches[p.id]===p.answer)
 const ready=full&&!!grade.trim()&&(!anthem||(puzzleDone&&matchDone))
 function swap(a:number,b:number){setTiles(old=>{const next=[...old];[next[a],next[b]]=[next[b],next[a]];return next});setSelected(null)}
 function send(){const msg=['تسليم أنشطة الكتاب - نغماتي','الدرس: '+lessonTitle,'الاسم الرباعي: '+name.trim(),'الصف: '+grade.trim(),...(anthem?['النشاط الأول - تركيب العلم: '+(puzzleDone?'مكتمل':'غير مكتمل'),'النشاط الثاني - توصيل الصور بالجمل: '+PROMPTS.map(p=>p.text+' ← '+(PICTURES.find(c=>c.id===matches[p.id])?.label||'لم تُجب')).join('؛ ')]:[])].join('\n');window.open('https://wa.me/'+PHONE+'?text='+encodeURIComponent(msg),'_blank','noopener,noreferrer')}
 return <section className="rounded-[2rem] bg-white p-4 md:p-6 shadow-chunky border-2 border-amber-200"><h3 className="text-2xl font-extrabold mb-4">📚 أنشطة الكتاب</h3>
 {anthem&&<div className="space-y-6">
 <div className="rounded-2xl bg-cream p-4"><h4 className="font-extrabold text-lg">النشاط الأول: ركّب صورة علم سلطنة عُمان 🧩</h4><p className="my-2">اسحب القطع إلى أماكنها الصحيحة. على الهاتف، اضغط على قطعتين لتبديل مكانهما.</p><div className="grid grid-cols-3 gap-1 max-w-xl mx-auto rounded-xl overflow-hidden border-2 border-slate-300">{tiles.map((piece,slot)=>{const row=Math.floor(piece/3),col=piece%3;return <button key={slot} draggable onDragStart={e=>{setDragged(String(slot));e.dataTransfer.setData('text/plain',String(slot))}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const from=Number(e.dataTransfer.getData('text/plain')||dragged);if(Number.isInteger(from)&&from!==slot)swap(from,slot);setDragged(null)}} onClick={()=>{if(selected===null)setSelected(slot);else if(selected===slot)setSelected(null);else swap(selected,slot)}} aria-label={'قطعة '+(slot+1)} className={'relative aspect-[4/3] overflow-hidden bg-white '+(selected===slot?'ring-4 ring-violet-500 z-10':'')+(piece===slot?'':' cursor-grab')} style={{backgroundImage:'url(https://raw.githubusercontent.com/arnoha98-hash/naghmati/main/oman-flag.jpg)',backgroundSize:'300% 300%',backgroundPosition:(col*50)+'% '+(row*50)+'%',touchAction:'manipulation'}}><span className="absolute bottom-1 right-1 rounded-full bg-white/90 px-2 text-xs font-bold text-slate-800">{slot+1}</span></button>})}</div><div className="flex flex-wrap gap-2 mt-3"><button onClick={()=>{setTiles([...INITIAL]);setSelected(null)}} className="rounded-full bg-white border px-4 py-2 font-bold">إعادة ترتيب القطع</button><span className={'rounded-full px-4 py-2 font-bold '+(puzzleDone?'bg-green-100 text-green-800':'bg-white text-slate-600')}>{puzzleDone?'أحسنت! ركّبت العلم 🎉':'رتّب القطع لتكوين العلم'}</span></div><p className="text-xs text-ink/60 mt-2">ملاحظة: هذا نموذج تركيب مقسّم إلى 9 قطع مستطيلة من صورة العلم المرفوعة.</p></div>
 <div className="rounded-2xl bg-cream p-4"><h4 className="font-extrabold text-lg">النشاط الثاني: رتّب الصور على الجمل</h4><p className="my-2">اسحب الصورة إلى الجملة المناسبة، أو اضغط على الصورة ثم على الجملة. لكل جملة صورة واحدة.</p><div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mb-4">{PICTURES.map(p=><button key={p.id} draggable onDragStart={e=>{setDragged(p.id);e.dataTransfer.setData('text/plain',p.id)}} onClick={()=>setDragged(p.id)} className={'rounded-2xl border-2 p-3 bg-white text-center '+(dragged===p.id?'border-violet-500 bg-violet-50':'border-slate-200')}><span className="block text-4xl mb-1">{p.emoji}</span><span className="font-bold text-sm">{p.label}</span></button>)}</div><div className="space-y-3">{PROMPTS.map(p=><div key={p.id} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain')||dragged;if(PICTURES.some(x=>x.id===id))setMatches(old=>({...old,[p.id]:id}));setDragged(null)}} onClick={()=>{if(dragged&&PICTURES.some(x=>x.id===dragged)){setMatches(old=>({...old,[p.id]:dragged}));setDragged(null)}}} className="flex items-center gap-3 rounded-xl border-2 border-slate-200 bg-white p-3 cursor-pointer"><span className="flex-1 font-bold">{p.text}</span><span className={'min-w-24 rounded-xl p-2 text-center '+(matches[p.id]?'bg-green-50 border border-green-300':'bg-slate-50 border border-dashed')}>{matches[p.id]?<><span className="block text-2xl">{PICTURES.find(x=>x.id===matches[p.id])?.emoji}</span><span className="text-xs">{PICTURES.find(x=>x.id===matches[p.id])?.label}</span></>:'ضع الصورة هنا'}</span></div>)}</div><div className="flex gap-2 items-center mt-3"><button onClick={()=>{setMatches({});setDragged(null)}} className="rounded-full bg-white border px-4 py-2 font-bold">مسح التوصيل</button><span className="text-sm font-bold">{matchDone?'أحسنت! كل الصور في أماكنها 🎉':''}</span></div><p className="text-xs text-ink/60 mt-2">الصور هنا رموز توضيحية مؤقتة. رابط صورة الشعب الذي أرسلته لا يفتح كملف صورة مباشر؛ أرسل الصورة نفسها كمرفق لأضعها هنا، وأضيف صورًا واضحة لليد الداعية والشرطة العُمانية.</p></div>
 </div>}
 <div className="mt-5 rounded-2xl border p-4"><h4 className="font-extrabold mb-3">بيانات التسليم</h4><label className="block font-bold">الاسم الرباعي</label><input className="w-full rounded-xl border p-3 my-2" value={name} onChange={e=>setName(e.target.value)} placeholder="اكتب الاسم الرباعي كاملًا"/><label className="block font-bold">الصف</label><input className="w-full rounded-xl border p-3 my-2" value={grade} onChange={e=>setGrade(e.target.value)} placeholder="مثال: الصف الأول / 1-أ"/><button disabled={!ready} onClick={send} className="mt-3 w-full rounded-full bg-green-600 p-3 font-extrabold text-white disabled:bg-slate-300">📲 تسليم الإجابات للمعلمة عبر واتساب</button>{!full&&<p className="text-sm text-rose-600 mt-2">اكتب الاسم الرباعي لتفعيل التسليم.</p>}{full&&!grade.trim()&&<p className="text-sm text-rose-600 mt-2">اكتب الصف لتفعيل التسليم.</p>}{anthem&&!puzzleDone&&<p className="text-sm text-rose-600 mt-2">أكمل تركيب العلم قبل التسليم.</p>}{anthem&&puzzleDone&&!matchDone&&<p className="text-sm text-rose-600 mt-2">أكمل توصيل الصور بالجمل قبل التسليم.</p>}<p className="text-xs mt-3 text-ink/60">ستُفتح رسالة واتساب جاهزة؛ اضغط إرسال داخل واتساب لإيصالها للمعلمة.</p></div></section>
}
