import { useState } from 'react'
const PHONE = '96898778983'
export default function BookActivities({lessonTitle}:{lessonTitle:string}) {
 const [name,setName]=useState(''),[grade,setGrade]=useState(''),[order,setOrder]=useState(''),[matches,setMatches]=useState<Record<string,string>>({})
 const anthem=lessonTitle==='النشيد الوطني'||lessonTitle==='نشيد (عَلَم بلادي)'
 const full=name.trim().split(/\s+/).filter(Boolean).length>=4
 const prompts=[['prayer','يا ربنا احفظ لنا جلالة السلطان'],['people','والشعب في الأوطان'],['pride','بالعز والأمان'],['sky','فارقتي هام السماء']]
 const choices=['صورة علم سلطنة عُمان','الأطفال','السماء والغيوم','اليد المرفوعة']
 const ready=full&&!!grade.trim()&&(!anthem||(!!order&&prompts.every(([k])=>!!matches[k])))
 function send(){const msg=['تسليم أنشطة الكتاب - نغماتي','الدرس: '+lessonTitle,'الاسم الرباعي: '+name.trim(),'الصف: '+grade.trim(),...(anthem?['النشاط الأول - ترتيب الألوان: '+order,'النشاط الثاني - التوصيل: '+prompts.map(([k,v])=>v+' ← '+matches[k]).join('؛ ')]:[])].join('\n');window.open('https://wa.me/'+PHONE+'?text='+encodeURIComponent(msg),'_blank')}
 return <section className="rounded-[2rem] bg-white p-4 md:p-6 shadow-chunky border-2 border-amber-200"><h3 className="text-2xl font-extrabold mb-4">📚 أنشطة الكتاب</h3>
 {anthem&&<div className="space-y-5"><div className="rounded-2xl bg-cream p-4"><h4 className="font-extrabold text-lg">النشاط الأول: ركّب علم سلطنة عُمان</h4><p className="my-2">اختر ترتيب الألوان الصحيح من أعلى العلم إلى أسفله.</p>{['أحمر، أبيض، أخضر','أبيض، أحمر، أخضر','أخضر، أبيض، أحمر'].map(x=><button key={x} onClick={()=>setOrder(x)} className={'m-1 rounded-xl border-2 p-3 font-bold '+(order===x?'border-violet-500 bg-violet-50':'border-slate-200 bg-white')}>{x}</button>)}</div>
 <div className="rounded-2xl bg-cream p-4"><h4 className="font-extrabold text-lg">النشاط الثاني: صِل العبارة بالصورة المناسبة</h4>{prompts.map(([k,v])=><label key={k} className="block rounded-xl bg-white p-3 my-2"><span className="block font-bold mb-2">{v}</span><select className="w-full rounded-lg border p-3 bg-white" value={matches[k]||''} onChange={e=>setMatches(old=>({...old,[k]:e.target.value}))}><option value="">اختَر الصورة...</option>{choices.map(c=><option key={c}>{c}</option>)}</select></label>)}</div></div>}
 <div className="mt-5 rounded-2xl border p-4"><h4 className="font-extrabold mb-3">بيانات التسليم</h4><label className="block font-bold">الاسم الرباعي</label><input className="w-full rounded-xl border p-3 my-2" value={name} onChange={e=>setName(e.target.value)} placeholder="اكتب الاسم الرباعي كاملًا"/><label className="block font-bold">الصف</label><input className="w-full rounded-xl border p-3 my-2" value={grade} onChange={e=>setGrade(e.target.value)} placeholder="مثال: الصف الأول / 1-أ"/><button disabled={!ready} onClick={send} className="mt-3 w-full rounded-full bg-green-600 p-3 font-extrabold text-white disabled:bg-slate-300">📲 تسليم الإجابات للمعلمة عبر واتساب</button>{!full&&<p className="text-sm text-rose-600 mt-2">اكتب الاسم الرباعي لتفعيل التسليم.</p>}{full&&!grade.trim()&&<p className="text-sm text-rose-600 mt-2">اكتب الصف لتفعيل التسليم.</p>}{anthem&&full&&grade.trim()&&!ready&&<p className="text-sm text-rose-600 mt-2">أكمل النشاطين قبل التسليم.</p>}<p className="text-xs mt-3 text-ink/60">ستُفتح رسالة واتساب جاهزة؛ اضغط إرسال داخل واتساب لإيصالها للمعلمة.</p></div></section>
}